services:
  app:
    build: .
    container_name: bff-back-for-frontend
    restart: unless-stopped
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    networks:
      - ticketti-network
    environment:
      SERVER_PORT: 8081
      SPRING_CONFIG_IMPORT: ${SPRING_CONFIG_IMPORT:-optional:configserver:http://config-server:8888}
      API_GATEWAY_URL: ${API_GATEWAY_URL:-http://api-gateway:8222}
      JWT_SECRET: ${JWT_SECRET:-clave-secreta-super-larga-de-minimo-32-caracteres}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports:
      - "8081:8081"

networks:
  ticketti-network:
    external: true
