services:
  app:
    build: .
    container_name: bff-back-for-frontend
    restart: unless-stopped
    networks:
      - ticketti-network
    environment:
      SERVER_PORT: 8081
      SPRING_CONFIG_IMPORT: ${SPRING_CONFIG_IMPORT}
      API_GATEWAY_URL: ${API_GATEWAY_URL}
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    ports:
      - "8081:8081"

networks:
  ticketti-network:
    external: true
