spring:
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
  application:
    name: bff-back-for-frontend
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

server:
  port: 8081

api:
  gateway:
    url: ${API_GATEWAY_URL:http://localhost:8222}

jwt:
  secret: ${JWT_SECRET:clave-secreta-super-larga-de-minimo-32-caracteres}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, threaddump
  endpoint:
    health:
      show-details: always
